// Code generated by goctl. DO NOT EDIT.
// Source: user_login.proto

package userloginclient

import (
	"context"

	"micro_service_user_login/user_login/user_login"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = user_login.Request
	Response = user_login.Response

	UserLogin interface {
		UserLogin(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultUserLogin struct {
		cli zrpc.Client
	}
)

func NewUserLogin(cli zrpc.Client) UserLogin {
	return &defaultUserLogin{
		cli: cli,
	}
}

func (m *defaultUserLogin) UserLogin(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := user_login.NewUserLoginClient(m.cli.Conn())
	return client.UserLogin(ctx, in, opts...)
}
