// Code generated by goctl. DO NOT EDIT.
// Source: user_login.proto

package server

import (
	"context"

	"micro_service_user_login/user_login/internal/logic"
	"micro_service_user_login/user_login/internal/svc"
	"micro_service_user_login/user_login/user_login"
)

type UserLoginServer struct {
	svcCtx *svc.ServiceContext
	user_login.UnimplementedUserLoginServer
}

func NewUserLoginServer(svcCtx *svc.ServiceContext) *UserLoginServer {
	return &UserLoginServer{
		svcCtx: svcCtx,
	}
}

func (s *UserLoginServer) UserLogin(ctx context.Context, in *user_login.Request) (*user_login.Response, error) {
	l := logic.NewUserLoginLogic(ctx, s.svcCtx)
	return l.UserLogin(in)
}
